[package]
name = "RocketEngine"
version = "0.1.0"
edition = "2024"

[dependencies]
minifb = "0.27"
winit = "0.30.12"
image = "0.25"
rapier2d = "0.22"
nalgebra = "0.33"

[[bin]]
name = "RocketEngine_Rapier"
path = "src/main_rapier.rs"


